services:
  app:
    container_name: ringscale-ai-template
    build: .
    restart: always
    ports:
      - "3009:3000"
    environment:
      DATABASE_URL: "postgresql://postgres.axouvddhktvhsigxbxfd:Ringscale%40123@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true"
      DIRECT_URL: "postgresql://postgres.axouvddhktvhsigxbxfd:Ringscale%40123@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres"
      NODE_ENV: production